
spring:
  datasource:
    druid:
      #基本属性 url、user、password
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      #配置初始化大小、最小、最大
      initial-size: 10
      min-idle: 50
      max-active: 300
      #配置获取连接等待超时的时间
      max-wait: 60000
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #连接校验
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置监控统计拦截的filters
      filters: stat
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
  redis:
    password:
    port: 6379
    pool:
      max-idle: 0
      max-active: 8
      max-wait: 5000
    host: localhost
    timeout: 0
  #应用名,也是注册到eureka的应用名
  application:
    name: base

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  config: classpath:logback.xml

#通过端点关闭程序
endpoints:
  shutdown:
    enabled: false

server:
  port: 8081

management:
  security:
    enabled: false #关掉安全认证
  port: 8088 #管理端口调整成8088
  context-path: /monitor #actuator的访问路径